default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: pikessoft

development:
  <<: *default
  database: punch_task_dev
test:
  <<: *default
  database: punch_task_test
production:
  <<: *default
  adapter: postgresql
  # adapter: mysql2
  database: punch_task_production
  # database: adsapp_production_dev
  username: root
  password: